### ISSUE TITLE
NPE when starting a container with network-mode container

### ISSUE THREAD

**Issue by christopherfrieler** [fabric8io/docker-maven-plugin#1055]
### Description
When starting a docker-container with network-mode container, this container "has no network", i.e. in the output of `docker inspect` the "Networks"-element is an empty JSON-object. This seems to be totally fine, as the container is running and reachable from the container the network belongs to.

However, the plugin runs into this NPE:
`[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.26.0:start (default-cli) on project pappa-mock: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.26.0:start failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.26.0:start (default-cli) on project pappa-mock: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.26.0:start failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.26.0:start failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: java.lang.NullPointerException
	at io.fabric8.maven.docker.model.ContainerDetails.getCustomNetworkIpAddresses(ContainerDetails.java:98)
	at io.fabric8.maven.docker.StartMojo.exposeContainerProps(StartMojo.java:392)
	at io.fabric8.maven.docker.StartMojo.waitForStartedContainer(StartMojo.java:186)
	at io.fabric8.maven.docker.StartMojo.executeInternal(StartMojo.java:143)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 22 more
`
, because `names()` on an empty JSON-object returns `null`, not an empty array. Hence, the plugin reports an error and stops the container again.

Probably a null-check in ContainerDetails would solve the issue.

Unfortunately I was not able to reproduce the problem in a minimal example. So there might be some more things necessary to run into the NPE.

### Workaround
As a workaround I prevent the execution of the code in ContainerDetails by setting `docker.exposeContainerInfo` to the empty string, switching off the exposure of container-infos.

### Info
* d-m-p version : tested with 0.25.2, 0.26.0 and 0.26.1, all were affected.
* Maven version (`mvn -v`) : 3.5.2
* Docker version : 18.03.1-ce, build 9ee9f40
* If it's a bug, how to reproduce : Execute `docker:start -Ddocker.network.mode=container -Ddocker.network.name=<a_container>` (with external properties enabled in the image-configuration).
* Sample project : Unfortunately I could not reproduce it in a minimal working example.

**Comment by rhuss** [comment]
Thanks for reporting! Yes, checking for an emptu Network seems leggit. See #1056 for a fix.
