### ISSUE TITLE
Exception when parsing Timestamp

### ISSUE THREAD

**Issue by jbennett2091** [fabric8io/docker-maven-plugin#1428]
### Description
Exception thrown parsing timestamp information for postgres

### Info
Exception in thread "Thread-6" java.time.format.DateTimeParseException: Text 'Error' could not be parsed at index 0
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
        at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:598)
        at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:583)
        at io.fabric8.maven.docker.util.TimestampFactory.createTimestamp(TimestampFactory.java:46)
        at io.fabric8.maven.docker.access.log.LogRequestor.callLogCallback(LogRequestor.java:200)
        at io.fabric8.maven.docker.access.log.LogRequestor.readStreamFrame(LogRequestor.java:173)
        at io.fabric8.maven.docker.access.log.LogRequestor.parseResponse(LogRequestor.java:186)
        at io.fabric8.maven.docker.access.log.LogRequestor.run(LogRequestor.java:104)

* d-m-p version :  0.34.1
* Maven version (`mvn -v`) :  3.6.3
```

```
* Docker version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by simontaen** [comment]
Same Issue here:

`
 Exception in thread "Thread-7" java.time.format.DateTimeParseException: Text 'Error' could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
        at java.time.ZonedDateTime.parse(ZonedDateTime.java:597)
        at java.time.ZonedDateTime.parse(ZonedDateTime.java:582)
        at io.fabric8.maven.docker.util.TimestampFactory.createTimestamp(TimestampFactory.java:46)
        at io.fabric8.maven.docker.access.log.LogRequestor.callLogCallback(LogRequestor.java:200)
        at io.fabric8.maven.docker.access.log.LogRequestor.readStreamFrame(LogRequestor.java:173)
        at io.fabric8.maven.docker.access.log.LogRequestor.parseResponse(LogRequestor.java:186)
        at io.fabric8.maven.docker.access.log.LogRequestor.run(LogRequestor.java:104)
`

* d-m-p version : 0.34.1
* Maven version: 3.5.2
* Java Version `openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
`

Let me know if I can be of any more help.

**Comment by rhuss** [comment]
Any idea how to get to the full logline that causes this error? The best fix would be to adapt the regexp expression that extracts the timestamp from the logline, but for that, I would need to know how the line (that contains the string "Error" in the place where a timestamp should be)
