### ISSUE TITLE
docker:run stuck at the end of the entrypoint/cmd execution

### ISSUE THREAD

**Issue by fabienmagagnosc** [fabric8io/docker-maven-plugin#1506]
### Description

There is a lock it seems, causing the maven build to stay stuck forever

### Info

* docker-maven-plugin version : 0.38.0
* Maven version (`mvn -v`) : 3.6.3
```

```
* Docker version : Docker version 20.10.11, build dea9396
* how to reproduce : simply execute an image build, and execute the script, docker:build docker:run docker:stop

When we do the thread dump, we can see that there is a lock :

- the entrypoint execution is finished
- the docker container is stopped (and deleted) 
- maven is stuck
- we can see a double lock in fabrio8 code (see below the thread dump)

_"main" #1 prio=5 os_prio=0 cpu=14825.61ms elapsed=1165.86s tid=0x00007fd7ac016800 nid=0x13505 in Object.wait()  [0x00007fd7b5794000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.13/Native Method)
	**- waiting on <0x00000000ce98fe18> (a io.fabric8.maven.docker.RunMojo)**
	at java.lang.Object.wait(java.base@11.0.13/Object.java:328)
	**at io.fabric8.maven.docker.StartMojo.executeInternal(StartMojo.java:183)
	- waiting to re-lock in wait() <0x00000000ce98fe18> (a io.fabric8.maven.docker.RunMojo)**
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:271)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.13/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.13/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.13/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.13/Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)_

**Comment by rhuss** [comment]
`docker:run` will always run in the foreground and blocks until killed with `CTRL-C`. You should use `docker:start` instead. See also https://dmp.fabric8.io/#docker:start
