### ISSUE TITLE
build failed: Conversion = '%'

### ISSUE THREAD

**Issue by aporo69** [fabric8io/docker-maven-plugin#457]
Hi,

I tried to setup a minimalistic maven projecct to try your plugin and I am getting a build failure with the following message:

> [INFO] DOCKER> Selecting previously unselected package init-system-helpers.
(Reading database ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 min
[INFO] Finished at: 2016-05-22T00:28:23+02:00
[INFO] Final Memory: 11M/87M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.15.2:build (Build Docker images) on project docker-maven-plugin-verbose-bug: Execution Build Docker images of goal io.fabric8:docker-maven-plugin:0.15.2:build failed: Conversion = '%' -> [Help 1

The thing is that error occurs only at the first time I build a container which means that once docker uses its cache, the error doesn't show up.

Here's what I get with a mvn -X:

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 59.692 s
[INFO] Finished at: 2016-05-22T00:40:19+02:00
[INFO] Final Memory: 11M/82M
[INFO] ------------------------------------------------------------------------
[DEBUG] Connection manager is shutting down
[DEBUG] http-outgoing-0: Close connection
[DEBUG] http-outgoing-0: Close connection
[DEBUG] Connection manager shut down
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.15.2:build (Build Docker images) on project docker-maven-plugin-verbose-bug: Execution Build Docker images of goal io.fabric8:docker-maven-plugin:0.15.2:build failed: Conversion = '%' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.15.2:build (Build Docker images) on project docker-maven-plugin-verbose-bug: Execution Build Docker images of goal io.fabric8:docker-maven-plugin:0.15.2:build failed: Conversion = '%'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution Build Docker images of goal io.fabric8:docker-maven-plugin:0.15.2:build failed: Conversion = '%'
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.util.UnknownFormatConversionException: Conversion = '%'
	at java.util.Formatter.checkText(Formatter.java:2579)
	at java.util.Formatter.parse(Formatter.java:2565)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2925)
	at io.fabric8.maven.docker.util.AnsiLogger.verbose(AnsiLogger.java:79)
	at io.fabric8.maven.docker.access.chunked.BuildJsonResponseHandler.process(BuildJsonResponseHandler.java:28)
	at io.fabric8.maven.docker.access.chunked.EntityStreamReaderUtil.processJsonStream(EntityStreamReaderUtil.java:26)
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient$HcChunckedResponseHandlerWrapper.handleResponse(DockerAccessWithHcClient.java:437)
	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler.handleResponse(ApacheHttpClientDelegate.java:167)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.post(ApacheHttpClientDelegate.java:93)
	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.buildImage(DockerAccessWithHcClient.java:194)
	at io.fabric8.maven.docker.service.BuildService.doBuildImage(BuildService.java:105)
	at io.fabric8.maven.docker.service.BuildService.buildImage(BuildService.java:62)
	at io.fabric8.maven.docker.AbstractBuildSupportMojo.buildImage(AbstractBuildSupportMojo.java:71)
	at io.fabric8.maven.docker.BuildMojo.buildAndTag(BuildMojo.java:46)
	at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:38)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:169)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

I am using Maven 3.3.3 with an OpenJDK 1.8.

Here is a sample project to reproduce the issue: [https://github.com/aporo69/docker-maven-plugin-issue-457]

Thank you for your help and keep up with the good job :)

**Comment by rhuss** [comment]
Thanks a lot for reporting this !

It's an regression introduced when formatting info messages has been added. this is fixed in the next relase.

**Comment by aporo69** [comment]
Thank you, and you're welcome :)
