### ISSUE TITLE
ClassNotFoundException in Version 0.15.6

### ISSUE THREAD

**Issue by shoutcool** [fabric8io/docker-maven-plugin#479]
After upgrading from 0.15.5 to 0.15.6 i got following exception:

java.lang.ClassNotFoundException: org.codehaus.plexus.util.Scanner
[17:09:43][Step 2/3] 	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[17:09:43][Step 2/3] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
[17:09:43][Step 2/3] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
[17:09:43][Step 2/3] 	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
[17:09:43][Step 2/3] 	... 125 more

after inserting the missing dependency it's working again:
`<plugin>`
`   <groupId>io.fabric8</groupId>`
`   <artifactId>docker-maven-plugin</artifactId>`
`   <version>0.15.6</version>`
`      <extensions>true</extensions>`
`      <dependencies>`
`         <dependency>`
`            <groupId>org.codehaus.plexus</groupId>`
`            <artifactId>plexus-utils</artifactId>`
`            <version>3.0.15</version>`
`         </dependency>`
`      </dependencies>`
`   <configuration>`

**Comment by rhuss** [comment]
yeah, sorry. will fix this ASAP, expect a 0.15.7 this evening.

Please stick to 0.15.5 in the meanwhile.

thanks ...

**Comment by rhuss** [comment]
0.15.7 is out with a fix. Could you please test this ?

Sorry for any inconvenience ...

**Comment by shoutcool** [comment]
works like expected!
thx for the quick fix
