### ISSUE TITLE
unable to retrieve container name

### ISSUE THREAD

**Issue by computerlyrik** [fabric8io/docker-maven-plugin#522]
Hi!

Since 0.15.10 i am seeing

`[ERROR] DOCKER> Unable to retrieve container name for [mycontaineralias]`

only if

```xml
							<run>
								<namingStrategy>alias</namingStrategy>
```

0.15.9 works as expected.

**Comment by rhuss** [comment]
Could you please let maven run with `-e` and post the exception you get ? (with some context around it). And if you have pom.xml to share, that would be awesome.

**Comment by rutherfordjw** [comment]
same issue here

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.15.10:stop (docker-clean) on project qmr-launch: Unable to retrieve container name for [qmr-launch]: No such container: qmr-launch (Not Found: 404) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.15.10:stop (docker-clean) on project qmr-launch: Unable to retrieve container name for [qmr-launch]
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
       	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
       	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
       	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
       	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
       	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
       	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
       	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
       	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
       	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:497)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to retrieve container name for [qmr-launch]
       	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:193)
       	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
       	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
       	... 20 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to retrieve container name for [qmr-launch]
       	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.inspectContainer(DockerAccessWithHcClient.java:248)
       	at io.fabric8.maven.docker.service.QueryService.getContainer(QueryService.java:54)
       	at io.fabric8.maven.docker.StopMojo.getContainersToStop(StopMojo.java:88)
       	at io.fabric8.maven.docker.StopMojo.stopContainers(StopMojo.java:74)
       	at io.fabric8.maven.docker.StopMojo.executeInternal(StopMojo.java:62)
       	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:190)
       	... 22 more
Caused by: io.fabric8.maven.docker.access.hc.http.HttpRequestException: No such container: qmr-launch (Not Found: 404)
       	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler.handleResponse(ApacheHttpClientDelegate.java:172)
       	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
       	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
       	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
       	at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.get(ApacheHttpClientDelegate.java:58)
       	at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.inspectContainer(DockerAccessWithHcClient.java:245)
       	... 27 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
