### ISSUE TITLE
NPE during docker:logs

### ISSUE THREAD

**Issue by tkruse** [fabric8io/docker-maven-plugin#612]
### Description

when running docker:logs, task fails with NPE. I guess would be easiet to provide Dockerfile, too, but it is confidential.

### Info

* d-m-p version : 0.17.1
* Maven version (`mvn -v`) : 3.3.9
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.17.1:logs (default-cli) on project
ven-plugin:0.17.1:logs failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:docker-maven-plugin:0.17.1:logs failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at io.fabric8.maven.docker.LogsMojo.executeInternal(LogsMojo.java:55)
        at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:193)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```
* Docker version :  1.12.0
* OS: Windows 7

My docker config:
```
<image>
							<name>%g/my_api:01</name>
							<alias>my_api</alias>
							<build>
								<dockerFileDir>${project.basedir}/dockerfiles/my_api</dockerFileDir>
								 <cmd>
									<!-- By default, start weblogic on docker start -->
						            <shell>/rms/dev/wls/domainA/startWebLogic.sh</shell>
								</cmd>
							</build>
							<run>
								<ports>
									<!-- Weblogic admin port -->
									<port>7001:7001</port>
								</ports>
							</run>
						</image>
```

**Comment by tkruse** [comment]
Additionally I can say that this image has a problem (that I wanted to debug using logs), such that after mvn docker:start, the container seems to be stopped, not running.

**Comment by tkruse** [comment]
And fixinf my problem, docker:logs works fine. So the issue happens when the container is not started after docker:start.

**Comment by rhuss** [comment]
Thanks for the report.

Yes, you are right, the logs assume that there is that the container is still running. I will add the proper check in case the container has been already stopped.

**Comment by tkruse** [comment]
thx
