### ISSUE TITLE
Invalid port mapping error during build

### ISSUE THREAD

**Issue by ppatierno** [fabric8io/docker-maven-plugin#698]
### Description

I'm trying to build a Docker image with following port mapping : 
```xml
<ports>
      <port>15671:5671</port>
      <port>15672:5672</port>
</ports>
```

but I receive the following error : 

[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.19.0:build (default) on project dispatch-router: Execution default of goal io.fabric8:docker-maven-plugin:0.19.0:build failed:
[ERROR] Invalid port mapping '15671:5671'
[ERROR] Required format: '<hostIP>(/tcp|udp)'

### Info

* d-m-p version : 0.19.0
* Maven version (`mvn -v`) :3.3.9
* Docker version : 1.13

**Comment by rhuss** [comment]
@ppatierno thanks for the report. I'm a bit puzzled as port mapping should happen only during `docker:run` not `docker:build`.

Would it be possible to post the whole plugin configuration ? And if you can run `mvn -e ...` and post the the stacktrace, that would be helpful, too.

**Comment by ppatierno** [comment]
Following the plugin part of the pom.xml (it's quite simple for now) : 

```xml
<plugin>
	<groupId>io.fabric8</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<configuration>
	    <verbose>true</verbose>
	    <images>
		<image>
		    <build>
		        <from>gordons/qpid-dispatch:${qpid-dispatch.version}</from>
		        <ports>
		            <port>15671:5671</port>
		            <port>15672:5672</port>
		        </ports>
		    </build>
		</image>
	    </images>
	</configuration>
	<executions>
	    <execution>
		<phase>package</phase>
		<goals>
		    <goal>build</goal>
		</goals>
	    </execution>
	</executions>
</plugin>
```

and here the stacktrace : 

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.19.0:build (default) on project dispatch-router: Execution default of goal io.fabric8:docker-maven-plugin:0.19.0:build failed: 
Invalid port mapping '15671:5671'
Required format: '<hostIP>(/tcp|udp)'
See the reference manual for more details
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal io.fabric8:docker-maven-plugin:0.19.0:build failed: 
Invalid port mapping '15671:5671'
Required format: '<hostIP>(/tcp|udp)'
See the reference manual for more details
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalArgumentException: 
Invalid port mapping '15671:5671'
Required format: '<hostIP>(/tcp|udp)'
See the reference manual for more details
	at io.fabric8.maven.docker.assembly.DockerFileBuilder.validatePortExposure(DockerFileBuilder.java:258)
	at io.fabric8.maven.docker.assembly.DockerFileBuilder.addPorts(DockerFileBuilder.java:243)
	at io.fabric8.maven.docker.assembly.DockerFileBuilder.content(DockerFileBuilder.java:105)
	at io.fabric8.maven.docker.assembly.DockerFileBuilder.write(DockerFileBuilder.java:82)
	at io.fabric8.maven.docker.assembly.DockerAssemblyManager.createDockerTarArchive(DockerAssemblyManager.java:111)
	at io.fabric8.maven.docker.service.ArchiveService.createArchive(ArchiveService.java:102)
	at io.fabric8.maven.docker.service.BuildService.buildImage(BuildService.java:66)
	at io.fabric8.maven.docker.AbstractBuildSupportMojo.buildImage(AbstractBuildSupportMojo.java:67)
	at io.fabric8.maven.docker.BuildMojoNoFork.buildAndTag(BuildMojoNoFork.java:55)
	at io.fabric8.maven.docker.BuildMojoNoFork.executeInternal(BuildMojoNoFork.java:46)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:208)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more

**Comment by rhuss** [comment]
ah, ok. Sorry, the `<ports>` section in the `<build>` part is used only for exposing ports in the generated image: https://dmp.fabric8.io/#build-configuration

You should move your port mapping to the `<run>` section, as port mapping is only useful when running containers:

```xml
<plugin>
	<groupId>io.fabric8</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<configuration>
	    <verbose>true</verbose>
	    <images>
		<image>
		    <build>
		        <from>gordons/qpid-dispatch:0.7.0</from>
                    </build>
                    <run>
		        <ports>
		            <port>15671:5671</port>
		            <port>15672:5672</port>
		        </run>
		    </build>
		</image>
	    </images>
	</configuration>
	<executions>
	    <execution>
		<phase>package</phase>
		<goals>
		    <goal>build</goal>
		</goals>
	    </execution>
	</executions>
</plugin>
```

Does this work for you ?

I agree, that the error message is misleading. will clean that up.

**Comment by ppatierno** [comment]
@rhuss so sorry ... the right way is using the ports under build for exposing, so something like

```xml
<ports>
   <port>5671</port>
   <port>5672</port>
</ports>
```

and then using the mapping 

```xml
<ports>
    <port>15671:5671</port>
    <port>15672:5672</port>
</ports>
```

under the run section.

Do I need both ?

**Comment by ppatierno** [comment]
But then the run section is needed only if I run the image using the fabric8 plugin.
I think that in my scenario I just need the simple :

```xml
<ports>
   <port>5671</port>
   <port>5672</port>
</ports>
```

inside the build.

**Comment by rhuss** [comment]
This translates into a "EXPOSE" line in the Dockerfile which you only need when using `docker run -P` as these ports are only meta data. During runtime you can still map every port without mentioning it here, so you can even remove it completely.

If you don't mind I'll close the issue, feel free to ask if you still have questions.

**Comment by thatsk** [comment]
nope its not working

**Comment by thatsk** [comment]
Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.25.0:build for parameter run: Cannot find 'run' in class io.fabric8.maven.docker.config.BuildImageConfiguration -> [Help 1]

Getting another error.
I am agree with @ppatierno that why can't we use under <ports> tab.
also if i try with only exposing one port.
							<ports>
							<port>8081</port>
							</ports>
it will work.
But if i attach
							<ports>
							<port>8081</port>
							</ports>
it will not work.

**Comment by rhuss** [comment]
> Unable to parse configuration of mojo io.fabric8:docker-maven-plugin:0.25.0:build for parameter run: Cannot find 'run' in class io.fabric8.maven.docker.config.BuildImageConfiguration -> [Help 1]

That's because your configuration is wrong. I suspect that you nest `<run>` within a `<build>`. 'should in parallel, but see the docs for more explanation.

Be also careful where you put the `<ports>` section (within `<build>` or `<run>`), they have different meanings and formats for each.

**Comment by thatsk** [comment]
Can you just provide small block pom.xml which should be ideal

**Comment by rhuss** [comment]
You could check out the samples, e.g. https://github.com/fabric8io/docker-maven-plugin/blob/master/samples/data-jolokia/pom.xml or even the manual in https://dmp.fabric8.io/#build-configuration (look for "ports" in the table) and https://dmp.fabric8.io/#start-port-mapping

**Comment by mickey4u** [comment]
@rhuss I have the same issue. Port mapping this way never works for me. 
```
   <run>
        <ports>
           <port>localhost:8080:8080</port>
           <port>localhost:8081:8081</port>
        </ports>
   </run>
```

But when I run the the image with the `-p` option it works perfectly.
