### ISSUE TITLE
Authentication fails when crendentials are provided in Maven settings

### ISSUE THREAD

**Issue by bjpe** [fabric8io/docker-maven-plugin#807]
### Description

I'm trying to build a Docker image using a private registry which requires authentication. When I provide my credentials using an `authConfig` section in the POM, it works, the same if I provide my username and password via `mvn -Ddocker.username=foo -Ddocker.password=bar`. However, if I use a `server` section in my `~/.m2/settings.xml`, I get the following error:

```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.21.0:build (default-cli) on project server: Unable to pull 'wildfly_oracle:10.1.0' from registry 'my.private.registry.io' : Get https://my.private.registry.io/v2/wildfly_oracle/manifests/10.1.0: unknown:
Authentication is required (Internal Server Error: 500) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.21.0:build (default-cli) on project server: Unable to pull 'wildfly_oracle:10.1.0' from registry 'my.private.registry.io' : Get https://my.private.registry.io/v2/wildfly_oracle/manifests/10.1.0: unknown: Authentication is required (Internal Server Error: 500)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to pull 'wildfly_oracle:10.1.0' from registry 'my.private.registry.io' : Get https:/my.private.registry.io/v2/wildfly_oracle/manifests/10.1.0: unknown: Authentication is required (Internal Server Error
: 500)
        at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:226)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to pull 'wildfly_oracle:10.1.0' from registry 'my.private.registry.io' : Get https://my.private.registry.io/v2/wildfly_oracle/manifests/10.1.0: unknown: Authentication is required (Internal Server
 Error: 500)
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pullImage(DockerAccessWithHcClient.java:358)
        at io.fabric8.maven.docker.service.RegistryService.checkImageWithAutoPull(RegistryService.java:81)
        at io.fabric8.maven.docker.service.BuildService.autoPullBaseImage(BuildService.java:211)
        at io.fabric8.maven.docker.service.BuildService.buildImage(BuildService.java:58)
        at io.fabric8.maven.docker.BuildMojo.buildAndTag(BuildMojo.java:58)
        at io.fabric8.maven.docker.BuildMojo.executeInternal(BuildMojo.java:44)
        at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
        ... 22 more
Caused by: io.fabric8.maven.docker.access.hc.http.HttpRequestException: Get https://my.private.registry.io/v2/wildfly_oracle/manifests/10.1.0: unknown: Authentication is required (Internal Server Error: 500)
        at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler.handleResponse(ApacheHttpClientDelegate.java:177)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
        at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.post(ApacheHttpClientDelegate.java:97)
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pullImage(DockerAccessWithHcClient.java:355)
        ... 28 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

My `settings.xml` contains the following configuration:

```
<servers>
  ...
  <!-- Docker -->
  <server>
    <id>my.private.registry.io</id>
    <username>foo</username>
    <password>bar</password>
  </server>
</servers>
```

### Info

* d-m-p version : 0.21.0
* Maven version (`mvn -v`) :
```
$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: C:\Program Files\maven\3.3.9
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_131\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```
* Docker version : Docker version 17.05.0-ce, build 89658be

**Comment by rhuss** [comment]
Does it work for "push" for you ? (E.g. pushing a created image with 'mvn docker:push' and specifying the creds in settings.xml)

**Comment by bjpe** [comment]
No, unfortunately not:

```
$ mvn -e -Dcis_version=local docker:push
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building server 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- docker-maven-plugin:0.21.0:push (default-cli) @ server ---
[INFO] DOCKER> Docker machine "default" is running
[INFO] DOCKER> DOCKER_HOST from docker-machine "default" : tcp://192.168.99.100:2376

[INFO] DOCKER> The push refers to a repository [my.private.registry.io/project]
####
[ERROR] DOCKER> Unable to push 'my.private.registry.io/project:local' from registry 'my.private.registry.io' : unknown: Authentication is required  [unknown: Authentication is required ]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.372 s
[INFO] Finished at: 2017-07-03T16:26:56+02:00
[INFO] Final Memory: 18M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.21.0:push (default-cli) on project server: Unable to push 'my.private.registry.io/project:local' from registry 'my.private.registry.io' : unknown: Authentication is required -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.21.0:push (default-cli) on project server: Unable to push 'my.private.registry.io/project:local' from registry 'my.private.registry.io' : unknown:
Authentication is required
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to push 'my.private.registry.io/project:local' from registry 'my.private.registry.io' : unknown: Authentication is required
        at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:226)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to push 'my.private.registry.io/project:local' from registry 'my.private.registry.io' : unknown: Authentication is required
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pushImage(DockerAccessWithHcClient.java:372)
        at io.fabric8.maven.docker.service.RegistryService.pushImages(RegistryService.java:49)
        at io.fabric8.maven.docker.PushMojo.executeInternal(PushMojo.java:38)
        at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:223)
        ... 22 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: unknown: Authentication is required
        at io.fabric8.maven.docker.access.chunked.PullOrPushResponseJsonHandler.throwDockerAccessException(PullOrPushResponseJsonHandler.java:45)
        at io.fabric8.maven.docker.access.chunked.PullOrPushResponseJsonHandler.process(PullOrPushResponseJsonHandler.java:22)
        at io.fabric8.maven.docker.access.chunked.EntityStreamReaderUtil.processJsonStream(EntityStreamReaderUtil.java:26)
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient$HcChunkedResponseHandlerWrapper.handleResponse(DockerAccessWithHcClient.java:652)
        at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler.handleResponse(ApacheHttpClientDelegate.java:172)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
        at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.post(ApacheHttpClientDelegate.java:97)
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.doPushImage(DockerAccessWithHcClient.java:584)
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pushImage(DockerAccessWithHcClient.java:370)
        ... 25 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

However, it works it I supply the username and password using `-Ddocker.username` and `-Ddocker.password`.

**Comment by rhuss** [comment]
Let's check a bit the settings.xml, since I'm pretty sure that it works in general (as it does for me all the time).

* Your `settings.xml` is located in `~/.m2` ?
* You don't override the settings.xml with `mvn -s` ?
* Could you [check with -X](https://stackoverflow.com/questions/1261215/maven-command-to-determine-which-settings-xml-file-maven-is-using) which settings.xml is used ?
* If all that doesn't help, could you post your settings.xml (with removing sensitive data before of course) ?

**Comment by bjpe** [comment]
Thank you, the third point finally unveiled the problem - way down in the POM, there was a profile providing an authConfig not suitable for my system. After removing this section, the Maven settings were correctly used.
Excuse me for any inconvenience and many thanks for your help!
