### ISSUE TITLE
docker-maven-plugin with 2 images - Neo4j and Elasticsearch

### ISSUE THREAD

**Issue by Artgit** [fabric8io/docker-maven-plugin#826]
I'm trying to configure two images - Neo4j and Elasticsearch

This is my configuration:

```
<plugin>
	<groupId>io.fabric8</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<version>0.21.0</version>

	<configuration>

		<showLogs>true</showLogs>

		<images>

			<image>
				<name>docker.elastic.co/elasticsearch/elasticsearch:5.5.1</name>
				<alias>elasticsearch</alias>
				<run>

					<ports>
						<port>${elasticsearch.http.port}:9200</port>
					</ports>

					<env>
						<xpack.security.enabled>false</xpack.security.enabled>
					</env>

					<wait>
						<http>
							<method>GET</method>
							<status>200</status>
							<url>http://${docker.host.address}:${elasticsearch.http.port}/_cat/health</url>
						</http>
						<time>60000</time>
					</wait>

				</run>
			</image>

			<image>
				<name>neo4j:${neo4j.version}</name>
				<alias>neo4j-database</alias>
				<run>

					<dependsOn>
						<container>elasticsearch</container>
					</dependsOn>

					<volumes>
						<bind>
							<volume>${project.basedir}/../docs/graphaware/plugins/${neo4j.version}:/plugins</volume>
						</bind>
					</volumes>

					<env>
						<NEO4J_AUTH>${neo4j.username}/${neo4j.password}</NEO4J_AUTH>
						<NEO4J_dbms_memory_pagecache_size>2G</NEO4J_dbms_memory_pagecache_size>
						<NEO4J_dbms_memory_heap_maxSize>2G</NEO4J_dbms_memory_heap_maxSize>

						<!-- GrapAware Framework and Elasticsearch plugin -->

						<NEO4J_dbms_unmanaged__extension__classes>com.graphaware.server=/graphaware</NEO4J_dbms_unmanaged__extension__classes>
						<NEO4J_com_graphaware_runtime_enabled>true</NEO4J_com_graphaware_runtime_enabled>
						<NEO4J_com_graphaware_module_ES_2>com.graphaware.module.es.ElasticSearchModuleBootstrapper</NEO4J_com_graphaware_module_ES_2>
						<NEO4J_com_graphaware_module_ES_keyProperty>ID()</NEO4J_com_graphaware_module_ES_keyProperty>
						<NEO4J_com_graphaware_module_ES_relationship>(false)</NEO4J_com_graphaware_module_ES_relationship>
						<NEO4J_com_graphaware_module_ES_uri>localhost</NEO4J_com_graphaware_module_ES_uri>
						<NEO4J_com_graphaware_module_ES_port>${elasticsearch.http.port}</NEO4J_com_graphaware_module_ES_port>
						<NEO4J_com_graphaware_module_ES_index>neo4j-index</NEO4J_com_graphaware_module_ES_index>
						<NEO4J_com_graphaware_module_ES_node>hasLabel('Decision') || hasLabel('Nomination')</NEO4J_com_graphaware_module_ES_node>

					</env>

					<ports>
						<port>${neo4j.http.port}:7474</port>
						<port>${neo4j.bolt.port}:7687</port>
					</ports>

					<wait>
						<http>
							<url>http://${docker.host.address}:${neo4j.http.port}/browser</url>
						</http>
						<time>60000</time>
					</wait>

				</run>
			</image>
		</images>
	</configuration>

	<executions>
		<execution>
			<id>prepare-neo4j-database</id>
			<phase>pre-integration-test</phase>
			<goals>
				<goal>start</goal>
			</goals>
		</execution>
		<execution>
			<id>remove-neo4j-database</id>
			<phase>post-integration-test</phase>
			<goals>
				<goal>stop</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Right now Elasticsearch stops working during the Neo4j startup.. but if I remove Elasticsearch or Neo4j(image declaration) then the single image(doesn't matter ES or Neo4j) starts working fine.

Whats wrong with my configuration and how to configure them to work together ?

This is a log:

```
([INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building domain 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:0.21.0:start (default-cli) @ domain ---
[INFO] DOCKER> [docker.elastic.co/elasticsearch/elasticsearch:5.5.1] "elasticsearch": Start container 4210a3c70ac4
[INFO] DOCKER> [docker.elastic.co/elasticsearch/elasticsearch:5.5.1] "elasticsearch": Waiting on url http://localhost:9250/_cat/health with method GET for status 200.
elasticsearch> [2017-07-25T19:10:32,324][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch> [2017-07-25T19:10:32,493][INFO ][o.e.e.NodeEnvironment    ] [C6-wCLD] using [1] data paths, mounts [[/ (overlay)]], net usable_space [51.7gb], net total_space [58.8gb], spins? [possibly], types [overlay]
elasticsearch> [2017-07-25T19:10:32,493][INFO ][o.e.e.NodeEnvironment    ] [C6-wCLD] heap size [1.9gb], compressed ordinary object pointers [true]
elasticsearch> [2017-07-25T19:10:32,495][INFO ][o.e.n.Node               ] node name [C6-wCLD] derived from node ID [C6-wCLDRRhK1W8o_BToEjA]; set [node.name] to override
elasticsearch> [2017-07-25T19:10:32,495][INFO ][o.e.n.Node               ] version[5.5.1], pid[1], build[19c13d0/2017-07-18T20:44:24.823Z], OS[Linux/4.9.36-moby/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_141/25.141-b16]
elasticsearch> [2017-07-25T19:10:32,495][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [aggs-matrix-stats]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [ingest-common]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [lang-expression]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [lang-groovy]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [lang-mustache]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [lang-painless]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [parent-join]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [percolator]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [reindex]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [transport-netty3]
elasticsearch> [2017-07-25T19:10:34,931][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded module [transport-netty4]
elasticsearch> [2017-07-25T19:10:34,933][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded plugin [ingest-geoip]
elasticsearch> [2017-07-25T19:10:34,933][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded plugin [ingest-user-agent]
elasticsearch> [2017-07-25T19:10:34,933][INFO ][o.e.p.PluginsService     ] [C6-wCLD] loaded plugin [x-pack]
elasticsearch> [2017-07-25T19:10:37,282][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/49] [Main.cc@128] controller (64 bit): Version 5.5.1 (Build ea13b9662915df) Copyright (c) 2017 Elasticsearch BV
elasticsearch> [2017-07-25T19:10:37,301][INFO ][o.e.d.DiscoveryModule    ] [C6-wCLD] using discovery type [zen]
elasticsearch> [2017-07-25T19:10:38,415][INFO ][o.e.n.Node               ] initialized
elasticsearch> [2017-07-25T19:10:38,415][INFO ][o.e.n.Node               ] [C6-wCLD] starting ...
elasticsearch> [2017-07-25T19:10:38,969][INFO ][o.e.t.TransportService   ] [C6-wCLD] publish_address {172.17.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch> [2017-07-25T19:10:38,991][INFO ][o.e.b.BootstrapChecks    ] [C6-wCLD] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elasticsearch> [2017-07-25T19:10:42,055][INFO ][o.e.c.s.ClusterService   ] [C6-wCLD] new_master {C6-wCLD}{C6-wCLDRRhK1W8o_BToEjA}{XCk39e8ERQW-B_2c5IBNPg}{172.17.0.2}{172.17.0.2:9300}{ml.enabled=true}, reason: zen-disco-elected-as-master ([0] nodes joined)
elasticsearch> [2017-07-25T19:10:42,105][INFO ][o.e.h.n.Netty4HttpServerTransport] [C6-wCLD] publish_address {172.17.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch> [2017-07-25T19:10:42,105][INFO ][o.e.n.Node               ] [C6-wCLD] started
elasticsearch> [2017-07-25T19:10:42,165][INFO ][o.e.g.GatewayService     ] [C6-wCLD] recovered [0] indices into cluster_state
elasticsearch> [2017-07-25T19:10:42,698][INFO ][o.e.m.j.JvmGcMonitorService] [C6-wCLD] [gc][4] overhead, spent [355ms] collecting in the last [1s]
elasticsearch> [2017-07-25T19:10:42,801][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [C6-wCLD] successfully created .ml-meta index template
elasticsearch> [2017-07-25T19:10:42,817][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [C6-wCLD] successfully created .ml-state index template
elasticsearch> [2017-07-25T19:10:42,831][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [C6-wCLD] successfully created .ml-notifications index template
elasticsearch> [2017-07-25T19:10:43,094][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [C6-wCLD] successfully created .ml-anomalies- index template
elasticsearch> [2017-07-25T19:10:43,144][INFO ][o.e.l.LicenseService     ] [C6-wCLD] license [4d582584-71d6-4a1f-a6a4-2f63c81a1f04] mode [trial] - valid
[INFO] DOCKER> [docker.elastic.co/elasticsearch/elasticsearch:5.5.1] "elasticsearch": Waited on url http://localhost:9250/_cat/health 15318 ms
[INFO] DOCKER> [neo4j:3.2.1] "neo4j-database": Start container e5f3dac177de
[INFO] DOCKER> [neo4j:3.2.1] "neo4j-database": Waiting on url http://localhost:7475/browser with method HEAD for status 200..399.
neo4j-database> Changed password for user 'neo4j'.
neo4j-database> Active database: graph.db
neo4j-database> Directories in use:
neo4j-database> home:         /var/lib/neo4j
neo4j-database> config:       /var/lib/neo4j/conf
neo4j-database> logs:         /var/lib/neo4j/logs
neo4j-database> plugins:      /plugins
neo4j-database> import:       /var/lib/neo4j/import
neo4j-database> data:         /var/lib/neo4j/data
neo4j-database> certificates: /var/lib/neo4j/certificates
neo4j-database> run:          /var/lib/neo4j/run
neo4j-database> Starting Neo4j.
neo4j-database> 2017-07-25 19:10:48.971+0000 WARN  Unknown config option: causal_clustering.discovery_listen_address
neo4j-database> 2017-07-25 19:10:48.972+0000 WARN  Unknown config option: causal_clustering.raft_advertised_address
neo4j-database> 2017-07-25 19:10:48.972+0000 WARN  Unknown config option: causal_clustering.raft_listen_address
neo4j-database> 2017-07-25 19:10:48.972+0000 WARN  Unknown config option: ha.host.coordination
neo4j-database> 2017-07-25 19:10:48.973+0000 WARN  Unknown config option: causal_clustering.transaction_advertised_address
neo4j-database> 2017-07-25 19:10:48.973+0000 WARN  Unknown config option: causal_clustering.discovery_advertised_address
neo4j-database> 2017-07-25 19:10:48.973+0000 WARN  Unknown config option: ha.host.data
neo4j-database> 2017-07-25 19:10:48.973+0000 WARN  Unknown config option: causal_clustering.transaction_listen_address
neo4j-database> 2017-07-25 19:10:49.011+0000 INFO  ======== Neo4j 3.2.1 ========
neo4j-database> 2017-07-25 19:10:49.040+0000 INFO  No SSL certificate found, generating a self-signed certificate..
neo4j-database> 2017-07-25 19:10:49.650+0000 INFO  Starting...
neo4j-database> 2017-07-25 19:10:50.507+0000 INFO  Bolt enabled on 0.0.0.0:7687.
neo4j-database> 2017-07-25 19:10:51.692+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime enabled, bootstrapping...
neo4j-database> 2017-07-25 19:10:51.718+0000 WARN  Topology change adapter is not available on community edition
neo4j-database> 2017-07-25 19:10:51.720+0000 INFO [c.g.r.b.RuntimeKernelExtension] Bootstrapping module with order 2, ID ES, using com.graphaware.module.es.ElasticSearchModuleBootstrapper
neo4j-database> 2017-07-25 19:10:51.782+0000 INFO  ElasticSearch index-prefix set to neo4j-index
neo4j-database> 2017-07-25 19:10:51.783+0000 INFO  ElasticSearch key-property set to uuid
neo4j-database> 2017-07-25 19:10:51.783+0000 INFO  ElasticSearch force-strings set to false
neo4j-database> 2017-07-25 19:10:51.860+0000 INFO  Node Inclusion Policy set to com.graphaware.common.policy.inclusion.composite.CompositeNodeInclusionPolicy@14d195a0
neo4j-database> 2017-07-25 19:10:51.862+0000 INFO  Relationship Inclusion Policy set to com.graphaware.common.policy.inclusion.composite.CompositeRelationshipInclusionPolicy@456106b5
neo4j-database> 2017-07-25 19:10:51.862+0000 INFO  Elasticsearch URI set to localhost
neo4j-database> 2017-07-25 19:10:51.863+0000 INFO  Elasticsearch port set to 9250
neo4j-database> 2017-07-25 19:10:51.863+0000 INFO  Elasticsearch key property set to ID()
neo4j-database> 2017-07-25 19:10:51.865+0000 INFO  ElasticSearch index-prefix set to neo4j-index
neo4j-database> 2017-07-25 19:10:51.866+0000 INFO  ElasticSearch key-property set to ID()
neo4j-database> 2017-07-25 19:10:51.868+0000 INFO  ElasticSearch force-strings set to false
neo4j-database> 2017-07-25 19:10:51.868+0000 INFO  Elasticsearch mapping configured with class com.graphaware.module.es.mapping.DefaultMapping
neo4j-database> 2017-07-25 19:10:51.892+0000 INFO  Registering module ES with GraphAware Runtime.
neo4j-database> 2017-07-25 19:10:51.897+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime bootstrapped, starting the Runtime...
neo4j-database> 2017-07-25 19:10:55.824+0000 INFO  Starting GraphAware...
neo4j-database> 2017-07-25 19:10:55.824+0000 INFO  Loading module metadata...
neo4j-database> 2017-07-25 19:10:55.825+0000 INFO  Loading metadata for module ES
neo4j-database> 2017-07-25 19:10:55.902+0000 INFO  Module ES seems to have been registered for the first time.
neo4j-database> 2017-07-25 19:10:55.902+0000 INFO  Module ES seems to have been registered for the first time, will try to initialize...
neo4j-database> 2017-07-25 19:10:55.904+0000 INFO  InitializeUntil set to 0 and it is 1501009855904. Will NOT initialize.
neo4j-database> 2017-07-25 19:10:55.905+0000 INFO  Creating fresh metadata for module ES.
neo4j-database> 2017-07-25 19:10:55.910+0000 INFO  Module ES has not changed configuration since last run, already initialized.
neo4j-database> 2017-07-25 19:10:56.125+0000 INFO  Module metadata loaded.
neo4j-database> 2017-07-25 19:10:56.125+0000 INFO  Starting transaction-driven modules...
neo4j-database> 2017-07-25 19:10:56.125+0000 INFO  Starting Elasticsearch Writer...
neo4j-database> 2017-07-25 19:10:56.131+0000 INFO  Creating Jest Client...
neo4j-database> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
neo4j-database> SLF4J: Defaulting to no-operation (NOP) logger implementation
neo4j-database> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
neo4j-database> 2017-07-25 19:10:56.176+0000 INFO  Created Jest Client.
neo4j-database> 2017-07-25 19:10:56.201+0000 ERROR Failed to create Elasticsearch index. org.apache.http.conn.HttpHostConnectException: Connect to localhost:9250 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
neo4j-database> java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:9250 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
neo4j-database> at com.graphaware.module.es.mapping.BaseMapping.lambda$createIndexAndMapping$13(BaseMapping.java:184)
neo4j-database> at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
neo4j-database> at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
neo4j-database> at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
neo4j-database> at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
neo4j-database> at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
neo4j-database> at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
neo4j-database> at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
neo4j-database> at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
neo4j-database> at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
neo4j-database> at com.graphaware.module.es.mapping.BaseMapping.createIndexAndMapping(BaseMapping.java:180)
neo4j-database> at com.graphaware.module.es.ElasticSearchWriter.createIndexIfNotExist(ElasticSearchWriter.java:156)
neo4j-database> at com.graphaware.module.es.ElasticSearchWriter.start(ElasticSearchWriter.java:77)
neo4j-database> at com.graphaware.runtime.module.thirdparty.WriterBasedThirdPartyIntegrationModule.start(WriterBasedThirdPartyIntegrationModule.java:61)
neo4j-database> at com.graphaware.module.es.ElasticSearchModule.start(ElasticSearchModule.java:85)
neo4j-database> at com.graphaware.runtime.manager.ProductionTxDrivenModuleManager.start(ProductionTxDrivenModuleManager.java:49)
neo4j-database> at com.graphaware.runtime.manager.BaseTxDrivenModuleManager.startModules(BaseTxDrivenModuleManager.java:113)
neo4j-database> at com.graphaware.runtime.TxDrivenRuntime.startModules(TxDrivenRuntime.java:147)
neo4j-database> at com.graphaware.runtime.ProductionRuntime.startModules(ProductionRuntime.java:70)
neo4j-database> at com.graphaware.runtime.BaseGraphAwareRuntime.start(BaseGraphAwareRuntime.java:134)
neo4j-database> at com.graphaware.runtime.bootstrap.RuntimeKernelExtension.lambda$start$9(RuntimeKernelExtension.java:117)
neo4j-database> at java.lang.Thread.run(Thread.java:748)
neo4j-database> Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:9250 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
neo4j-database> at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
neo4j-database> at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
neo4j-database> at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
neo4j-database> at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
neo4j-database> at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
neo4j-database> at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
neo4j-database> at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
neo4j-database> at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
neo4j-database> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
neo4j-database> at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
neo4j-database> at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:47)
neo4j-database> at com.graphaware.module.es.mapping.BaseMapping.createIndexAndMapping(BaseMapping.java:198)
neo4j-database> at com.graphaware.module.es.mapping.BaseMapping.lambda$createIndexAndMapping$13(BaseMapping.java:182)
neo4j-database> ... 21 more
neo4j-database> Caused by: java.net.ConnectException: Connection refused (Connection refused)
neo4j-database> at java.net.PlainSocketImpl.socketConnect(Native Method)
neo4j-database> at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
neo4j-database> at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
neo4j-database> at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
neo4j-database> at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
neo4j-database> at java.net.Socket.connect(Socket.java:589)
neo4j-database> at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
neo4j-database> at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
neo4j-database> ... 33 more
neo4j-database> 2017-07-25 19:10:56.203+0000 INFO  Started Elasticsearch Writer.
neo4j-database> 2017-07-25 19:10:56.203+0000 INFO  Transaction-driven modules started.
neo4j-database> 2017-07-25 19:10:56.203+0000 INFO  There are no timer-driven runtime modules. Not scheduling any tasks.
neo4j-database> 2017-07-25 19:10:56.203+0000 INFO  GraphAware started.
neo4j-database> 2017-07-25 19:10:56.203+0000 INFO [c.g.r.b.RuntimeKernelExtension] GraphAware Runtime automatically started.
neo4j-database> 2017-07-25 19:10:57.630+0000 INFO  Started.
neo4j-database> 2017-07-25 19:10:57.995+0000 INFO [c.g.s.f.b.GraphAwareServerBootstrapper] started
neo4j-database> 2017-07-25 19:10:57.997+0000 INFO  Mounted unmanaged extension [com.graphaware.server] at [/graphaware]
neo4j-database> 2017-07-25 19:10:58.134+0000 INFO  Google Analytics enabled
neo4j-database> 2017-07-25 19:10:58.150+0000 INFO  Mounting GraphAware Framework at /graphaware
neo4j-database> 2017-07-25 19:10:58.159+0000 INFO  Will try to scan the following packages: {com.**.graphaware.**,org.**.graphaware.**,net.**.graphaware.**}
neo4j-database> 2017-07-25 19:11:00.004+0000 INFO  Remote interface available at http://localhost:7474/
[INFO] DOCKER> [neo4j:3.2.1] "neo4j-database": Waited on url http://localhost:7475/browser 31648 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.710 s
[INFO] Finished at: 2017-07-25T22:11:16+03:00
[INFO] Final Memory: 22M/509M
[INFO] ------------------------------------------------------------------------)

```

**Comment by rhuss** [comment]
Elasticsearch container is not stopped, but you can't connect with the neo4j container via localhost to elasticsearch. 

You better setup a network link or custom network to combine both.

**Comment by Artgit** [comment]
I'm reading the documentation on links or network but can't configure this by myself. I also tried to add: 								

`<net>host</net>							`

with no luck.

Could you please show how to extend my config in order to create a proper link or network in order to combine both ?

**Comment by Artgit** [comment]
I have also tried to add:

```
<links>
    <link>elasticsearch:elasticsearch</link>
</links>
```

to neo4j image config, but still no luck with the following output:

```
neo4j-database> 2017-07-26 08:18:46.080+0000 ERROR Failed to create Elasticsearch index. org.apache.http.conn.ConnectTimeoutException: Connect to elasticsearch:9250 [elasticsearch/172.17.0.2] failed: connect timed out
neo4j-database> java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to elasticsearch:9250 [elasticsearch/172.17.0.2] failed: connect timed out
```

**Comment by Artgit** [comment]
Also the interesting thing:

When I invoke 

`mvn docker:stop -Dfile.encoding=UTF-8`

the only "neo4j-database" stops.. "elasticsearch" is absent that means that this container was stopped previously.

```
D:\Projects\decisionwanted\domain>mvn docker:stop -Dfile.encoding=UTF-8
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building domain 0.0.1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- docker-maven-plugin:0.21.0:stop (default-cli) @ domain ---
[INFO] DOCKER> [neo4j:3.2.1] "neo4j-database": Stop and removed container c0c02328aa64 after 0 ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.566 s
```

**Comment by Artgit** [comment]
I have also added mongodb image, so I have 3 images now - mongo, elasticsearch, neo4j

after `docker:start` start the `docker ps` command shows only 2 containers:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
7190dd570f2b        neo4j:3.2.1         "/docker-entrypoin..."   28 seconds ago      Up 26 seconds       7473/tcp, 0.0.0.0:7475->7474/tcp, 0.0.0.0:7688->7687/tcp   festive_morse
e19d64ac4677        mongo:3.4.6         "docker-entrypoint..."   44 seconds ago      Up 43 seconds       0.0.0.0:27018->27017/tcp                                   elated_hypatia
```

How to find the issue with elasticsearch ?

**Comment by IgorDomshchikov** [comment]
@Artgit, I have the same issue.

My configuration looks like this:

```
<image>
								<name>docker.elastic.co/elasticsearch/elasticsearch:${es.version}</name>
								<alias>elasticsearch</alias>
								<run>
									<ports>
										<port>${elasticsearch.http.port}:9200</port>
										<port>${elasticsearch.transport.port}:9300</port>
									</ports>
									<env>
										<xpack.security.enabled>false</xpack.security.enabled>
										<cluster.name>elasticsearch</cluster.name>
									</env>
									<wait>
										<http>
											<method>GET</method>
											<status>200</status>
											<url>http://${docker.host.address}:${elasticsearch.http.port}/_cat/health</url>
										</http>
										<time>60000</time>
									</wait>
								</run>
							</image>

							<image>
								<name>neo4j:${neo4j.version}</name>
								<alias>neo4j-database</alias>
								<run>
									<dependsOn>
										<container>elasticsearch</container>
									</dependsOn>
									<ports>
										<port>${neo4j.http.port}:7474</port>
										<port>${neo4j.bolt.port}:7687</port>
									</ports>
									<volumes>
										<bind>
											<volume>${project.basedir}/../docs/graphaware/plugins/${neo4j.version}:/plugins</volume>
										</bind>
									</volumes>
									<env>
										<NEO4J_AUTH>${neo4j.username}/${neo4j.password}</NEO4J_AUTH>
										<NEO4J_dbms_memory_pagecache_size>2G</NEO4J_dbms_memory_pagecache_size>
										<NEO4J_dbms_memory_heap_maxSize>2G</NEO4J_dbms_memory_heap_maxSize>

										<NEO4J_dbms_unmanaged__extension__classes>com.graphaware.server=/graphaware</NEO4J_dbms_unmanaged__extension__classes>
										<NEO4J_com_graphaware_runtime_enabled>true</NEO4J_com_graphaware_runtime_enabled>
										<NEO4J_com_graphaware_module_ES_2>com.graphaware.module.es.ElasticSearchModuleBootstrapper</NEO4J_com_graphaware_module_ES_2>
										<NEO4J_com_graphaware_module_ES_keyProperty>ID()</NEO4J_com_graphaware_module_ES_keyProperty>
										<NEO4J_com_graphaware_module_ES_relationship>(false)</NEO4J_com_graphaware_module_ES_relationship>
										<NEO4J_com_graphaware_module_ES_uri>elasticsearch</NEO4J_com_graphaware_module_ES_uri>
										<NEO4J_com_graphaware_module_ES_port>9200</NEO4J_com_graphaware_module_ES_port>
										<NEO4J_com_graphaware_module_ES_index>neo4j-index</NEO4J_com_graphaware_module_ES_index>
										<NEO4J_com_graphaware_module_ES_node>hasLabel('Decision') || hasLabel('Nomination')</NEO4J_com_graphaware_module_ES_node>
										
										<NEO4J_dbms_security_procedures_unrestricted>apoc.*</NEO4J_dbms_security_procedures_unrestricted>
										<NEO4J_apoc_trigger_enabled>true</NEO4J_apoc_trigger_enabled>
									</env>
									<links>
										<link>elasticsearch:elasticsearch</link>
									</links>
									<wait>
										<http>
											<url>http://${docker.host.address}:${neo4j.http.port}/browser</url>
										</http>
										<time>60000</time>
									</wait>
								</run>
							</image>

```

**NOTE:** I am getting this issue only on Mac machine. 

Do you know how to solve it?
