### ISSUE TITLE
Assembly jar using Dockerfile with artifact or artifact-with-dependencies descriptorRef throws ClassNotFoundException

### ISSUE THREAD

**Issue by anasirvent** [fabric8io/docker-maven-plugin#885]
I'm trying to build a docker image on a very simple spring boot application using Dockerfile.
When running `mvn docker:build` everything seems fine and I have this output

INFO] --- docker-maven-plugin:0.22.1:build (default-cli) @ plugin-test ---
[INFO] Copying files to /Users/asirvent/Documents/workspace_test/test/target/docker/springboot/test/build/maven
[INFO] Building tar: /Users/asirvent/Documents/workspace_test/test/target/docker/springboot/test/tmp/docker-build.tar
[INFO] DOCKER> [springboot/test:latest]: Created docker-build.tar in 2 seconds
[INFO] DOCKER> [springboot/test:latest]: Built image sha256:85556
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

But if I try to run a container from the built image I'm getting  the following error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at test.test.App.main(App.java:17)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

My assumption is I have some kind of misconfiguration in the assembly, as I can execute the jar produced in /target without any problem , but the jar inside /target/docker/springboot/test/build/maven always throws this ClassNotFoundException.
I have tried also using artifact as descriptorRef but it throws the same error.

Plugin configuration:

```
<plugin>
	<groupId>io.fabric8</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<version>${docker.maven.plugin.version}</version>
	<configuration>
		<images>
			<image>
				<name>springboot/test</name>
				<build> 
					<dockerFile>Dockerfile</dockerFile>
                                <assembly>
                                    <descriptorRef>artifact-with-dependencies</descriptorRef>
                                </assembly>
				</build>
			</image>
		</images>
	</configuration>
				
	<executions>
		<execution>
			<id>docker-build</id>
			<goals>
				<goal>build</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Dockerfile
```
FROM java:latest
VOLUME /tmp
ADD maven/${project.build.finalName}.jar /app.jar
EXPOSE 8080
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar
```

The whole project can be found here: https://github.com/anasirvent/mavendockerplugintest.

docker maven plugin version: 0.22.1
Docker version 17.09.0-ce, build afdb6d4

**Comment by anasirvent** [comment]
It was a case of misconfiguration of the pom with spring boot versions and including the correct parent.
Docker containers are now running the application properly.
