### ISSUE TITLE
Configuration error: <image> must have a non-null <name>

### ISSUE THREAD

**Issue by maximilian-schott** [fabric8io/docker-maven-plugin#909]
### Description

Having the simple configuration of:

```xml
<configuration>
    <showLogs>true</showLogs>
    <autoCreateCustomNetworks>true</autoCreateCustomNetworks>
    <images>
        <image>
            <alias>database</alias>
            <name>database-${env.BRANCH_NAME}-${env.BUILD_ID}</name>
            <external>
                <type>compose</type>
                <basedir>${project.basedir}/docker</basedir>
                <composeFile>docker-compose.yml</composeFile>
            </external>
            <run>
                <network>
                    <mode>custom</mode>
                    <name>itests-${env.BRANCH_NAME}-${env.BUILD_ID}</name>
                    <alias>database</alias>
                </network>
            </run>
        </image>
    </images>
</configuration>
```

With docker-compose.yml:

```yml
version: '2'
services:
  database:
    container_name: postgis-${BRANCH_NAME}-${BUILD_ID}
    image: custom-registry/postgis:9.6-german-geo
    tmpfs:
      - /var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
```

Produces the error:

```sh
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.23.0:build (container-setup) on project aloxerv: Execution container-setup of goal io.fabric8:docker-maven-plugin:0.23.0:build failed: Configuration error: <image> must have a non-null <name> -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:docker-maven-plugin:0.23.0:build (container-setup) on project aloxerv: Execution container-setup of goal io.fabric8:docker-maven-plugin:0.23.0:build failed: Configuration error: <image> must have a non-null <name>
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution container-setup of goal io.fabric8:docker-maven-plugin:0.23.0:build failed: Configuration error: <image> must have a non-null <name>
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Configuration error: <image> must have a non-null <name>
	at io.fabric8.maven.docker.config.ConfigHelper.verifyImageNames(ConfigHelper.java:124)
	at io.fabric8.maven.docker.config.ConfigHelper.resolveConfiguration(ConfigHelper.java:114)
	at io.fabric8.maven.docker.config.ConfigHelper.resolveImages(ConfigHelper.java:50)
	at io.fabric8.maven.docker.AbstractDockerMojo.initImageConfiguration(AbstractDockerMojo.java:307)
	at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:214)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

### Info

* d-m-p version : 0.23.0
* Maven version : 3.5.0
* Docker version : 17.11.0-ce

This appears to be a bug, as clearly the <name> tag in the plugin config in the pom.xml isn't empty.

**Comment by jobs2altaf** [comment]
I have the same issue. The service name in the docker-compose.xml was wrong and not matching with the maven artifact name .

docker-compose.xml
services:
some-other-name:

**Comment by rhuss** [comment]
The compose support is a bit behind, so there could be indeed bugs like these. And this is indeed a bug. Anyone wanting to help to analyse and fix the issue ? I can assist with some pointer, but otherwise I have to much on my plate to fix it on my own.

**Comment by nikleo-eng** [comment]
I have faced the same issue with a local builded Dockerfile and not only with a pulled image; fortunally I have found a simple workaround, that works perfectly with the build goal of the plugin.

Plugin configuration in pom.xml:

```
<plugin>
	<groupId>io.fabric8</groupId>
	<artifactId>docker-maven-plugin</artifactId>
	<version>0.39.1</version>
	<configuration>
		<autoCreateCustomNetworks>true</autoCreateCustomNetworks>
		<images>
			<image>
				<alias>${project.artifactId}</alias>
				<name>
					${project.groupId}/${project.artifactId}:${project.version}
				</name>
				<external>
					<type>compose</type>
					<basedir>${project.basedir}</basedir>
					<composeFile>docker-compose.yml</composeFile>
				</external>
				<run>
					<wait>
						<log>Application Started</log>
						<time>60</time>
					</wait>
				</run>
			</image>
		</images>
	</configuration>
	<executions>
		<execution>
			<id>docker-build-image</id>
			<phase>package</phase>
			<goals>
				<goal>build</goal>
			</goals>
		</execution>
		<execution>
			<id>docker-verify</id>
			<phase>verify</phase>
			<goals>
				<goal>start</goal>
				<goal>stop</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```
Referenced docker-compose.yml:

```
version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # You can now specify both a build and an image key if you're using the new file format.
    # docker-compose build will build the image and tag it with the name you've specified,
    # while docker-compose pull will attempt to pull it.
    # https://github.com/docker/compose/releases/tag/1.6.0
    # Workaround for issues:
    # https://github.com/fabric8io/docker-maven-plugin/issues/614
    # https://github.com/fabric8io/docker-maven-plugin/issues/909
    image: app:latest
    container_name: app_container
    networks:
      - custom-network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge 
```
(the referenced Dockerfile of the app service is not important for the replica of this issue)

The configuration line `image: app:latest` does all: it is a workaround for the issue and it is not used at all in the build goal of the plugin, that build the local referenced Dockerfile.
