### ISSUE TITLE
docker:start does not respect docker:build

### ISSUE THREAD

**Issue by mzakes** [fabric8io/docker-maven-plugin#949]
### Description

After upgrading to version 0.24.0 a container that's build during **docker:build** stage can't be started. It seems that the plugin tries to pull it.

docker:build
```
[INFO] DOCKER> Removing intermediate container 416cd1343c8c
[INFO] DOCKER> Successfully built e7b7f3224a14
[INFO] DOCKER> [test-container:latest] "build-test-container": Built image sha256:e7b7f
[INFO] DOCKER> [test-container:latest] "build-test-container": Removed old image sha256:720aa
```

docker:start
```
Caused by: org.apache.maven.plugin.MojoExecutionException: I/O Error
        at io.fabric8.maven.docker.StartMojo.executeInternal(StartMojo.java:175)
        at io.fabric8.maven.docker.AbstractDockerMojo.execute(AbstractDockerMojo.java:221)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: io.fabric8.maven.docker.access.DockerAccessException: Unable to pull 'test-container:latest' : repository test-container not found: does not exist or no pull access (Not Found: 404)
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pullImage(DockerAccessWithHcClient.java:377)
        at io.fabric8.maven.docker.service.RegistryService.pullImageWithPolicy(RegistryService.java:97)
        at io.fabric8.maven.docker.StartMojo.prepareStart(StartMojo.java:309)
        at io.fabric8.maven.docker.StartMojo.executeInternal(StartMojo.java:121)
        ... 23 more
Caused by: io.fabric8.maven.docker.access.hc.http.HttpRequestException: repository test-container not found: does not exist or no pull access (Not Found: 404)
        at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler.handleResponse(ApacheHttpClientDelegate.java:177)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at io.fabric8.maven.docker.access.hc.ApacheHttpClientDelegate.post(ApacheHttpClientDelegate.java:97)
        at io.fabric8.maven.docker.access.hc.DockerAccessWithHcClient.pullImage(DockerAccessWithHcClient.java:374)
        ... 26 more
```

Downgrade to 0.23.0 resolves the problem

### Info

* d-m-p version : 0.24.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Java version: 1.8.0_144, vendor: Oracle Corporation
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
* Docker version : 1.13.1, build 092cba3

**Comment by rhuss** [comment]
Yes, the `autoPull` behaviour has been changed slightly in 0.24.0.

From the [changelog](https://github.com/fabric8io/docker-maven-plugin/blob/master/doc/changelog.md):

> Please note that autoPullMode is deprecated now and the behaviour of the autoPullMode == always has been changed slightly so that now, it really always pulls the image from the registry. Also removeAll for docker:remove is deprecated in favor of removeMode (and the default mode has changed slightly). Please refer to the documentation for more information.

Actually, you have to change your `autoPullMode` from `always` to `on` (or ommit autoPull since `on` is the default)

Does this solve your problem ?

**Comment by rhuss** [comment]
Actually, you should move from `autoPull` to the new config option `imagePullPolicy`. Please refer to the documentation for details.

**Comment by mzakes** [comment]
Thanks for pointing out to the note  in the changelog about `Always ` behavior. This did the trick.
However, switching to `IfNotPresent` option has a higher impact. Now in the CI pipeline I need to ensure that all the images are removed from local repository before I run the tests. In other case I can get stale images which was not the case when using the `Always` option.
