### ISSUE TITLE
Joda dependency expected but not found on start image

### ISSUE THREAD

**Issue by stickycode** [fabric8io/docker-maven-plugin#971]
### Description

When running an image after build it fails to process the log files
```
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/joda/time/format/DateTimeParser
        at org.joda.time.format.ISODateTimeFormat$Constants.dateElementParser(ISODateTimeFormat.java:1347)
        at org.joda.time.format.ISODateTimeFormat$Constants.<clinit>(ISODateTimeFormat.java:1314)
        at org.joda.time.format.ISODateTimeFormat.dateTime(ISODateTimeFormat.java:773)
        at io.fabric8.maven.docker.util.Timestamp.<init>(Timestamp.java:60)
        at io.fabric8.maven.docker.access.log.LogRequestor.callLogCallback(LogRequestor.java:211)
        at io.fabric8.maven.docker.access.log.LogRequestor.readStreamFrame(LogRequestor.java:178)
        at io.fabric8.maven.docker.access.log.LogRequestor.parseResponse(LogRequestor.java:193)
        at io.fabric8.maven.docker.access.log.LogRequestor.run(LogRequestor.java:108)
```

### Info

* d-m-p version : 0.24.0
* Maven version (`mvn -v`) : 3.5.0
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T07:39:06+12:00)
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_NZ, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-36-generic", arch: "amd64", family: "unix"
```
* Docker version :  1.13.1

**Comment by rhuss** [comment]
That looks like a real strange error, as it seems to be an internal dependency error which I never have seen before. 

Do you have a minimal pom.xml which we could use to reproduce it ?

thanks ...

**Comment by stromnet** [comment]
I accidentally saw the same thing due to #978: If logging configuration is enabled, `mvn docker:start` will fire up the logging tracker, just before maven & the JVM exits.
I guess the LogDispatcher runs in some background thread?
